# Generated by Django 3.1.12 on 2025-05-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocVoitures', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
